apiVersion: apps/v1
kind: Deployment
metadata:
  name: meal-prep-app
spec:
  replicas: 1
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: meal-prep-app
  template:
    metadata:
      labels:
        app: meal-prep-app
    spec:
      nodeSelector:
      containers:
      - name: meal-prep-app
        image: gcr.io/meal-prep-261313/app
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: meal-prep-app
  labels:
    app: meal-prep-app
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: meal-prep-app